import json
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from . import get_llm

def validator_node(state: dict) -> dict:
    """
    Validates the outputs from the parallel agents for coherence and relevance.
    """
    llm = get_llm("llama3-8b-8192") # Faster model for validation
    
    system_prompt = """
    You are a meticulous validator for an AI system. Your job is to review the reports generated by four specialized agents: RBI Compliance, PESTEL, Competitor, and Trend.
    
    The original user query is: "{user_query}"
    The user's core intent is: "{analysis_intent}"
    
    You will be given the four reports. Your task is to assess them for:
    1.  **Relevance**: Does the report directly address the user's query and intent?
    2.  **Coherence**: Is the information within the report logical and consistent?
    3.  **Hallucination**: Does the report contain information that seems fabricated or not grounded in reality (e.g., naming non-existent competitors, citing non-existent laws)?
    
    You must respond with a JSON object only.
    
    The JSON object must have the following keys:
    - "is_valid": boolean (true if all reports are generally good, false if one or more are severely flawed)
    - "reason": string (Provide a brief reason for your decision. If invalid, specify which report is problematic and why.)
    
    Example JSON:
    {{
        "is_valid": true,
        "reason": "All reports are relevant and coherent."
    }}
    
    Example JSON:
    {{
        "is_valid": false,
        "reason": "The Competitor report seems to have hallucinated a company named 'FinBank India' which does not exist. Please re-run the competitor search."
    }}
    """
    
    human_prompt = f"""
    RBI Compliance Report:
    ---
    {state.get('rbig_compliance_report', 'Not generated.')}
    ---
    
    PESTEL Report:
    ---
    {state.get('pestel_report', 'Not generated.')}
    ---
    
    Competitor Report:
    ---
    {state.get('competitor_report', 'Not generated.')}
    ---
    
    Trend Report:
    ---
    {state.get('trend_report', 'Not generated.')}
    ---
    
    Validate these reports based on the system prompt.
    """
    
    formatted_prompt = system_prompt.format(user_query=state['user_query'], analysis_intent=state['analysis_intent'])
    messages = [SystemMessage(content=formatted_prompt), HumanMessage(content=human_prompt)]
    response = llm.invoke(messages)
    
    try:
        content = json.loads(response.content)
        return {
            "validation_status": "valid" if content.get("is_valid", False) else "invalid",
            "validation_reason": content.get("reason", "No reason provided.")
        }
    except json.JSONDecodeError:
        return {
            "validation_status": "invalid",
            "validation_reason": "Validator agent failed to produce a valid JSON response. Re-running agents."
        }